#!/bin/bash

# Exit immediately if any script errors
set -e

# Comment row above and uncomment line below for additional debug output
#set -ex

# Variables accessible to other scripts executed by this process
source ${FULLNODE}/bitcoin/variables

# Load some tools we might need
source ${FULLNODE}/bitcoin/tools

# Install bitcoin
source ${FULLNODE}/bitcoin/install

## TODO consider adding some interactive input for the software below?

# Install iceweasel
sudo apt-get install iceweasel -y

# Install tor
sudo apt-get install -y tor

# Install openvpn
sudo apt-get install -y openvpn

# Install resolvconf
sudo apt-get install -y resolvconf

